#!/usr/bin/env python3
"""Enrich maths and engineering university-details.json."""

import json
from pathlib import Path

BASE = Path(__file__).parent / "src/data"
MATHS_FILE = BASE / "maths/university-details.json"
ENG_FILE = BASE / "engineering/university-details.json"

# Common social/contact data keyed by standard slug
SOCIALS = {
    "oxford": {"instagram": "https://www.instagram.com/oxford_uni/", "twitter": "https://twitter.com/UniofOxford", "youtube": "https://www.youtube.com/oxford", "tiktok": "https://www.tiktok.com/@uni.of.oxford", "linkedin": "https://www.linkedin.com/school/oxforduni/"},
    "cambridge": {"instagram": "https://www.instagram.com/cambridgeuniversity/", "twitter": "https://twitter.com/Cambridge_Uni", "youtube": "https://www.youtube.com/cambridgeuniversity", "tiktok": "https://www.tiktok.com/@cambridgeuniversity", "linkedin": "https://www.linkedin.com/school/university-of-cambridge/"},
    "imperial": {"instagram": "https://www.instagram.com/imperialcollege/", "twitter": "https://twitter.com/imperialcollege", "youtube": "https://www.youtube.com/channel/UCcRV5FPxxWFdS4Fjnk9FQvA", "tiktok": "https://www.tiktok.com/@imperialcollege", "linkedin": "https://www.linkedin.com/school/imperial-college-london/"},
    "durham": {"instagram": "https://www.instagram.com/durhamuniversity/", "twitter": "https://twitter.com/durham_uni", "youtube": "https://www.youtube.com/user/durhamuniversity", "linkedin": "https://www.linkedin.com/school/durham-university/"},
    "edinburgh": {"instagram": "https://www.instagram.com/edinburghuniversity/", "twitter": "https://twitter.com/EdinburghUni", "youtube": "https://www.youtube.com/user/EdinburghUniversity", "tiktok": "https://www.tiktok.com/@edinburghuniversity", "linkedin": "https://www.linkedin.com/school/university-of-edinburgh/"},
    "warwick": {"instagram": "https://www.instagram.com/uniofwarwick/", "twitter": "https://twitter.com/uniofwarwick", "youtube": "https://www.youtube.com/@uniofwarwick", "tiktok": "https://www.tiktok.com/@uniofwarwick", "linkedin": "https://www.linkedin.com/school/uniofwarwick/"},
    "bristol": {"instagram": "https://www.instagram.com/universityofbristol/", "twitter": "https://twitter.com/bristoluni", "youtube": "https://www.youtube.com/UniversityOfBristol", "tiktok": "https://www.tiktok.com/@officialbristoluni", "linkedin": "https://www.linkedin.com/school/university-of-bristol/"},
    "st-andrews": {"instagram": "https://www.instagram.com/st.andrewsuniversity/", "twitter": "https://twitter.com/univofstandrews", "youtube": "https://www.youtube.com/univofstandrews", "tiktok": "https://www.tiktok.com/@standrewsuni", "linkedin": "https://www.linkedin.com/school/university-of-st-andrews/"},
    "bath": {"instagram": "https://www.instagram.com/uniofbath/", "twitter": "https://twitter.com/UniofBath", "youtube": "https://www.youtube.com/c/uniofbath", "tiktok": "https://www.tiktok.com/@uniofbath", "linkedin": "https://www.linkedin.com/school/university-of-bath/"},
    "surrey": {"instagram": "https://www.instagram.com/uniofsurrey/", "twitter": "https://twitter.com/UniofSurrey", "youtube": "https://www.youtube.com/user/universityofsurrey", "tiktok": "https://www.tiktok.com/@uniofsurrey", "linkedin": "https://www.linkedin.com/school/university-of-surrey/"},
    "ucl": {"instagram": "https://www.instagram.com/ucl/", "twitter": "https://twitter.com/ucl", "youtube": "https://www.youtube.com/universitycollegelondon", "tiktok": "https://www.tiktok.com/@uclofficial", "linkedin": "https://www.linkedin.com/school/university-college-london/"},
    "southampton": {"instagram": "https://www.instagram.com/uni_southampton/", "twitter": "https://twitter.com/unisouthampton", "youtube": "https://www.youtube.com/universityofsouthampton", "tiktok": "https://www.tiktok.com/@unisouthampton", "linkedin": "https://www.linkedin.com/school/university-of-southampton/"},
    "manchester": {"instagram": "https://www.instagram.com/officialuom/", "twitter": "https://twitter.com/officialuom", "youtube": "https://www.youtube.com/@officialuom", "tiktok": "https://www.tiktok.com/@officialuom", "linkedin": "https://www.linkedin.com/school/university-of-manchester/"},
    "nottingham": {"instagram": "https://www.instagram.com/uniofnottingham/", "twitter": "https://twitter.com/UniofNottingham", "youtube": "https://www.youtube.com/nottmuniversity", "tiktok": "https://www.tiktok.com/@uniofnottingham", "linkedin": "https://www.linkedin.com/school/university-of-nottingham/"},
    "york": {"instagram": "https://www.instagram.com/uniofyork/", "twitter": "https://twitter.com/UniofYork", "youtube": "https://www.youtube.com/user/universityofyork", "tiktok": "https://www.tiktok.com/@uniofyork", "linkedin": "https://www.linkedin.com/school/university-of-york/"},
    "leicester": {"instagram": "https://www.instagram.com/uniofleicester/", "twitter": "https://twitter.com/uniofleicester", "youtube": "https://www.youtube.com/leicesteruniversity", "tiktok": "https://www.tiktok.com/@uniofleicester", "linkedin": "https://www.linkedin.com/school/university-of-leicester/"},
    "kcl": {"instagram": "https://www.instagram.com/kingscollegelondon/", "twitter": "https://twitter.com/KingsCollegeLon", "youtube": "https://www.youtube.com/kingscollegelondon", "tiktok": "https://www.tiktok.com/@kingscollegelondon", "linkedin": "https://www.linkedin.com/school/king's-college-london/"},
    "glasgow": {"instagram": "https://www.instagram.com/uofglasgow/", "twitter": "https://twitter.com/UofGlasgow", "youtube": "https://www.youtube.com/universityofglasgow", "tiktok": "https://www.tiktok.com/@uofglasgow", "linkedin": "https://www.linkedin.com/school/university-of-glasgow/"},
    "leeds": {"instagram": "https://www.instagram.com/universityofleeds/", "twitter": "https://twitter.com/UniversityLeeds", "youtube": "https://www.youtube.com/universityofleeds", "tiktok": "https://www.tiktok.com/@universityofleeds", "linkedin": "https://www.linkedin.com/school/university-of-leeds/"},
    "sheffield": {"instagram": "https://www.instagram.com/sheffielduni/", "twitter": "https://twitter.com/sheffielduni", "youtube": "https://www.youtube.com/sheffielduniversity", "tiktok": "https://www.tiktok.com/@sheffielduni", "linkedin": "https://www.linkedin.com/school/university-of-sheffield/"},
    "birmingham": {"instagram": "https://www.instagram.com/unibirmingham/", "twitter": "https://twitter.com/unibirmingham", "youtube": "https://www.youtube.com/unibirmingham", "tiktok": "https://www.tiktok.com/@unibirmingham", "linkedin": "https://www.linkedin.com/school/university-of-birmingham/"},
    "cardiff": {"instagram": "https://www.instagram.com/cardiffuni/", "twitter": "https://twitter.com/cardiffuni", "youtube": "https://www.youtube.com/cardiffuniversity", "tiktok": "https://www.tiktok.com/@cardiffuni", "linkedin": "https://www.linkedin.com/school/cardiff-university/"},
    "newcastle": {"instagram": "https://www.instagram.com/newcastleuni/", "twitter": "https://twitter.com/UniofNewcastle", "youtube": "https://www.youtube.com/newcastleuniversity", "tiktok": "https://www.tiktok.com/@newcastleuni", "linkedin": "https://www.linkedin.com/school/newcastle-university/"},
    "liverpool": {"instagram": "https://www.instagram.com/livuni/", "twitter": "https://twitter.com/LivUni", "youtube": "https://www.youtube.com/liverpooluniversity", "tiktok": "https://www.tiktok.com/@liverpooluni", "linkedin": "https://www.linkedin.com/school/university-of-liverpool/"},
    "exeter": {"instagram": "https://www.instagram.com/uniofexeter/", "twitter": "https://twitter.com/UniofExeter", "youtube": "https://www.youtube.com/user/universityofexeter", "tiktok": "https://www.tiktok.com/@uniofexeter", "linkedin": "https://www.linkedin.com/school/university-of-exeter/"},
    "sussex": {"instagram": "https://www.instagram.com/sussexuni/", "twitter": "https://twitter.com/SussexUni", "youtube": "https://www.youtube.com/sussexuniversity", "tiktok": "https://www.tiktok.com/@sussexuni", "linkedin": "https://www.linkedin.com/school/university-of-sussex/"},
    "loughborough": {"instagram": "https://www.instagram.com/lborouniversity/", "twitter": "https://twitter.com/lborouniversity", "youtube": "https://www.youtube.com/lborouniversity", "tiktok": "https://www.tiktok.com/@lborouniversity", "linkedin": "https://www.linkedin.com/school/loughborough-university/"},
    "queens-belfast": {"instagram": "https://www.instagram.com/qubofficial/", "twitter": "https://twitter.com/QUBelfast", "youtube": "https://www.youtube.com/queensuniversitybelfast", "tiktok": "https://www.tiktok.com/@qubofficial", "linkedin": "https://www.linkedin.com/school/queen's-university-belfast/"},
}

# Maths-specific data: slug -> (website, ref_rating, research_strengths, top_employers, emp_rate, salary, rep_snippet)
MATHS_DATA = {
    "oxford": ("https://www.ox.ac.uk", 1, 1, "GPA 3.61/4.0 — Mathematical Sciences #1 UK (REF 2021)", ["Pure mathematics and algebra", "Number theory and arithmetic geometry", "Mathematical physics", "Probability and statistics", "Applied and computational mathematics"], "Goldman Sachs, Jane Street, G-Research, GCHQ, McKinsey, D.E. Shaw, Citadel", 97, "£45,000", "Oxford's Mathematical Institute is the world's finest, producing a disproportionate share of Fields Medallists. Its 4-year MMath is the UK gold standard, and Oxford mathematicians dominate quantitative finance, data science and academic research."),
    "cambridge": ("https://www.cam.ac.uk", 1, 1, "GPA 3.65/4.0 — Mathematical Sciences #1 UK (REF 2021)", ["Pure mathematics and analysis", "Combinatorics and discrete mathematics", "Theoretical physics interface", "Probability and stochastic processes", "Applied mathematics and fluid dynamics"], "Goldman Sachs, Jane Street, D.E. Shaw, Citadel, GCHQ, DeepMind, McKinsey", 97, "£46,000", "Cambridge's Mathematics Faculty (Part III is the most famous postgraduate course in mathematics anywhere) produces Fields Medallists, FRS and the world's top quant traders. The Mathematical Tripos is the most demanding undergraduate maths degree in the world."),
    "imperial-college-london": ("https://www.imperial.ac.uk", 5, 5, "GPA 3.48/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and mathematical physics", "Statistics and data science", "Financial mathematics", "Numerical analysis and scientific computing", "Mathematical biology"], "Goldman Sachs, Jane Street, G-Research, McKinsey, DeepMind, Rolls-Royce, GCHQ", 97, "£42,000", "Imperial's Department of Mathematics has world-class research in applied mathematics, statistics and mathematical finance. The MEng Mathematics programmes are uniquely placed between pure mathematics and industry application."),
    "warwick": ("https://warwick.ac.uk", 7, 6, "GPA 3.42/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics (algebra, geometry, topology)", "Statistics and probability", "Combinatorics and discrete mathematics", "Mathematical analysis", "Ergodic theory"], "Goldman Sachs, G-Research, Jane Street, GCHQ, McKinsey, PwC, Citadel", 95, "£38,000", "Warwick Mathematics Institute is consistently ranked in the UK top 5 and is internationally renowned for algebra, analysis and combinatorics. Warwick's MASDOC doctoral centre is one of the UK's elite mathematics PhD programmes."),
    "durham": ("https://www.durham.ac.uk", 4, 4, "GPA 3.25/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Mathematical physics", "Statistics and probability", "Computational mathematics", "Mathematical biology"], "Goldman Sachs, PwC, Deloitte, GCHQ, BAE Systems, Rolls-Royce, Barclays", 94, "£34,000", "Durham's Department of Mathematical Sciences has a strong research reputation and a distinctive collegiate culture that creates close-knit academic communities. Durham mathematics graduates are sought after in finance, consulting and government."),
    "edinburgh": ("https://www.ed.ac.uk", 5, 6, "GPA 3.34/4.0 — Mathematical Sciences (REF 2021)", ["Algebra and number theory", "Mathematical physics and quantum field theory", "Statistics and data science", "Operational research", "Applied analysis"], "Goldman Sachs, Jane Street, Standard Life Aberdeen, PwC, Deloitte, GCHQ, DeepMind", 93, "£35,000", "Edinburgh's School of Mathematics is one of the UK's top 6, with particular strengths in algebraic geometry, mathematical physics and statistics. The Scottish 4-year Honours structure provides valuable breadth."),
    "bristol": ("https://www.bristol.ac.uk", 11, 10, "GPA 3.32/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and number theory", "Mathematical physics and quantum chaos", "Applied mathematics and fluid dynamics", "Statistics and probability", "Combinatorics"], "Goldman Sachs, Jane Street, G-Research, PwC, Deloitte, Rolls-Royce, Airbus", 93, "£35,000", "Bristol's School of Mathematics is internationally recognised, particularly for number theory, quantum chaos and mathematical physics. Bristol consistently produces graduates who enter quantitative finance at the highest levels."),
    "st-andrews": ("https://www.st-andrews.ac.uk", 2, 2, "GPA 3.35/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Fluid dynamics and mathematical modelling", "Statistics and data science", "Mathematical physics", "Applied mathematics"], "Goldman Sachs, PwC, Deloitte, GCHQ, Standard Life Aberdeen, BAE Systems, Baillie Gifford", 93, "£33,000", "St Andrews' School of Mathematics and Statistics is one of Scotland's finest, with a particularly strong reputation for applied mathematics, fluid dynamics and statistics. The beautiful campus and collegiate atmosphere make it an exceptional place to study."),
    "bath": ("https://www.bath.ac.uk", 9, 8, "GPA 3.18/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and mathematical modelling", "Statistics and probability", "Financial mathematics", "Numerical analysis", "Combinatorics"], "Goldman Sachs, PwC, Deloitte, Rolls-Royce, BAE Systems, GCHQ, Nationwide", 96, "£35,000", "Bath's Department of Mathematical Sciences has a strong reputation for applied mathematics and statistics, underpinned by the mandatory placement year that distinguishes Bath graduates. Bath financial mathematics graduates are particularly sought after."),
    "surrey": ("https://www.surrey.ac.uk", 30, 29, "GPA 3.03/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and modelling", "Statistics and data science", "Financial mathematics", "Computational mathematics", "Mathematics for biology"], "Goldman Sachs (Surrey proximity to London), PwC, Deloitte, BAE Systems, National Physical Laboratory, Rolls-Royce, GSK", 94, "£31,000", "Surrey's Department of Mathematics has a strong applied focus and benefits enormously from the mandatory Professional Training Year. Surrey mathematics graduates are disproportionately represented in City quantitative roles given the university's proximity to London."),
    "university-college-london": ("https://www.ucl.ac.uk", 8, 8, "GPA 3.40/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and analysis", "Statistics and probability", "Mathematical physics", "Computational mathematics", "Applied mathematics"], "Goldman Sachs, Jane Street, G-Research, PwC, McKinsey, DeepMind, Citadel", 95, "£38,000", "UCL's Department of Mathematics is world-class, ranked in the global top 20. Its London location and Russell Group status give graduates unrivalled access to City quantitative finance roles, tech firms and consulting."),
    "southampton": ("https://www.southampton.ac.uk", 12, 11, "GPA 3.16/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and fluid dynamics", "Statistics and operational research", "Pure mathematics", "Mathematical finance", "Computational mathematics"], "Goldman Sachs, Rolls-Royce, BAE Systems, IBM, PwC, Deloitte, GCHQ", 92, "£31,500", "Southampton's School of Mathematical Sciences has strong research in statistics, operational research and applied mathematics. Southampton's engineering heritage gives mathematics graduates an edge in aerospace and defence employers."),
    "manchester": ("https://www.manchester.ac.uk", 16, 14, "GPA 3.29/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Applied mathematics", "Statistics and probability", "Numerical methods", "Mathematical biology"], "Goldman Sachs, Jane Street, PwC, McKinsey, Deloitte, GCHQ, BAE Systems", 93, "£34,000", "Manchester's Department of Mathematics has a long tradition of world-class research. With 25 Nobel laureates and global top 35 ranking, Manchester mathematics graduates are highly sought after in finance and technology."),
    "nottingham": ("https://www.nottingham.ac.uk", 17, 16, "GPA 3.14/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Mathematical physics", "Applied mathematics", "Statistics and probability", "Mathematical finance"], "Goldman Sachs, PwC, Deloitte, Capital One, Experian, GCHQ, Rolls-Royce", 91, "£30,500", "Nottingham's School of Mathematical Sciences has a strong research base with particular strengths in algebra, mathematical physics and applied mathematics. Nottingham's proximity to major East Midlands employers in finance and industry is a practical advantage."),
    "york": ("https://www.york.ac.uk", 15, 14, "GPA 3.22/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Applied mathematics", "Statistics and data science", "Mathematical finance", "Computational mathematics"], "Goldman Sachs, PwC, Deloitte, GCHQ, Nestlé, Rolls-Royce, Yorkshire financial firms", 91, "£31,000", "York's Department of Mathematics has a strong research reputation with a particularly warm and supportive academic environment. York's collegiate Russell Group structure and beautiful campus make it an excellent choice for mathematics."),
    "leicester": ("https://le.ac.uk", 38, 37, "GPA 2.95/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Applied mathematics", "Statistics", "Mathematical modelling", "History of mathematics"], "Goldman Sachs, PwC, Deloitte, Walgreens Boots Alliance, NHS, GCHQ, Santander", 88, "£28,000", "Leicester's Department of Mathematics has a friendly, supportive culture and strong teaching reputation. Leicester's history in DNA fingerprinting (Alec Jeffreys) reflects the university's applied science tradition that permeates its mathematics programme."),
    "king-s-college-london": ("https://www.kcl.ac.uk", 22, 20, "GPA 3.29/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and analysis", "Mathematical physics and string theory", "Statistics and probability", "Applied mathematics", "Financial mathematics"], "Goldman Sachs, JP Morgan, PwC, Deloitte, GCHQ, McKinsey, Barclays", 94, "£37,000", "King's Department of Mathematics is world-class, with particularly strong research in mathematical physics and string theory. KCL's central London campuses provide exceptional access to City quantitative finance employers and major consulting firms."),
    "glasgow": ("https://www.gla.ac.uk", 20, 19, "GPA 3.31/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Statistics and data science", "Applied mathematics", "Mathematical physics", "Operational research"], "Goldman Sachs, Standard Life Aberdeen, PwC Scotland, Deloitte Scotland, GCHQ, BAE Systems, Baillie Gifford", 91, "£31,000", "Glasgow's School of Mathematics and Statistics has excellent research and teaching in pure mathematics, statistics and mathematical physics. Scotland's #2 university by most rankings, Glasgow mathematics graduates have strong access to Scotland's financial services sector."),
    "leeds": ("https://www.leeds.ac.uk", 11, 12, "GPA 3.22/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and fluid mechanics", "Pure mathematics and algebra", "Statistics and probability", "Mathematical biology", "Computational mathematics"], "Goldman Sachs, PwC, Deloitte, HSBC, First Direct, FERA Science, GCHQ", 92, "£31,000", "Leeds' School of Mathematics has strong research and excellent applied mathematics strengths, reflecting the university's engineering tradition. Leeds is the UK's largest financial centre outside London, giving mathematics graduates excellent regional employer access."),
    "sheffield": ("https://www.sheffield.ac.uk", 19, 17, "GPA 3.08/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Applied mathematics and modelling", "Statistics and probability", "Financial mathematics", "Computational mathematics"], "Goldman Sachs, PwC, Deloitte, GCHQ, National Grid, Rolls-Royce, Yorkshire financial firms", 91, "£30,000", "Sheffield's School of Mathematics and Statistics has a strong research base and friendly departmental culture. Sheffield is consistently voted one of the UK's best student cities, combining good mathematics with an excellent quality of life."),
    "birmingham": ("https://www.birmingham.ac.uk", 23, 22, "GPA 3.11/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Applied mathematics", "Mathematical physics", "Statistics", "Combinatorics"], "Goldman Sachs, PwC, Deloitte, KPMG, HSBC, Jaguar Land Rover (numerical), GCHQ", 91, "£30,500", "Birmingham's School of Mathematics has a strong research tradition and good employer links. Birmingham's central location and Russell Group status make it popular with mathematics students seeking strong career outcomes across finance and technology."),
    "cardiff": ("https://www.cardiff.ac.uk", 29, 27, "GPA 3.06/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and mathematical physics", "Analysis and topology", "Statistics and operational research", "Numerical methods", "Mathematical modelling"], "Goldman Sachs, PwC Wales, Deloitte, GCHQ, Admiral Insurance, Welsh Government, KPMG", 89, "£29,000", "Cardiff's School of Mathematics has particular strengths in applied mathematics and is the home of the world-renowned Gravity Exploration Institute. As the only Russell Group university in Wales, Cardiff mathematics graduates are well-positioned in both UK and Welsh employer markets."),
    "newcastle": ("https://www.ncl.ac.uk", 22, 21, "GPA 3.10/4.0 — Mathematical Sciences (REF 2021)", ["Statistics and probability", "Applied mathematics", "Pure mathematics", "Mathematical physics", "Computational mathematics"], "Goldman Sachs, PwC, Deloitte, Sage Group, Procter & Gamble, GCHQ, NHS", 90, "£30,000", "Newcastle's School of Mathematics, Statistics and Physics has a strong research and teaching reputation, with particular strengths in statistics and applied mathematics. Newcastle's vibrant student city and strong North East employer network are significant advantages."),
    "liverpool": ("https://www.liverpool.ac.uk", 28, 26, "GPA 3.06/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and algebra", "Mathematical physics", "Applied mathematics", "Statistics", "Computational mathematics"], "Goldman Sachs, PwC, Deloitte, GCHQ, Unilever (mathematical modelling), BAE Systems, NHS", 89, "£29,000", "Liverpool's Department of Mathematical Sciences has a long tradition of research excellence, particularly in pure mathematics and mathematical physics. Liverpool is one of the most vibrant and affordable major UK cities, making it a popular choice for mathematics students."),
    "exeter": ("https://www.exeter.ac.uk", 10, 12, "GPA 3.13/4.0 — Mathematical Sciences (REF 2021)", ["Applied mathematics and mathematical modelling", "Statistics and data science", "Climate mathematics and geophysical fluid dynamics", "Mathematical physics", "Numerical analysis"], "Goldman Sachs, PwC, Deloitte, Met Office (Exeter HQ), Environment Agency, BAE Systems, GCHQ", 91, "£30,500", "Exeter's Department of Mathematics and Statistics has particular strengths in climate mathematics and applied mathematics, reflecting the university's world-leading environmental science research. The Met Office headquarters is adjacent to campus, creating unique opportunities."),
    "sussex": ("https://www.sussex.ac.uk", 35, 33, "GPA 2.98/4.0 — Mathematical Sciences (REF 2021)", ["Pure mathematics and analysis", "Mathematical physics", "Statistics and probability", "Applied mathematics", "Mathematical biology"], "Goldman Sachs, PwC, Deloitte, Amex (Brighton), BAE Systems, GCHQ, NHS", 88, "£28,500", "Sussex's Department of Mathematics has a distinctive interdisciplinary character and strong links to the sciences. Sussex's proximity to Brighton's growing tech sector and London provides good employer access for mathematics graduates."),
}

# Engineering-specific data
ENG_DATA = {
    "cambridge": ("https://www.cam.ac.uk", 1, 1, "GPA 3.62/4.0 — Engineering (REF 2021)", ["Aerospace and turbomachinery (Whittle Lab)", "Thermodynamics and energy systems", "Structural mechanics and materials", "Electrical and electronic systems", "Manufacturing and production engineering"], "Rolls-Royce, BAE Systems, Airbus, ARM Holdings, McKinsey, Goldman Sachs, GCHQ", 98, "£46,000", "Cambridge's Engineering department is the largest in the UK and one of the best in the world. The Whittle Laboratory for gas turbine aerodynamics is globally pre-eminent. All students take a broad 2-year general engineering programme before specialising."),
    "oxford": ("https://www.ox.ac.uk", 1, 1, "GPA 3.59/4.0 — Engineering (REF 2021)", ["Mechanical and structural engineering", "Electrical and electronic systems", "Biomedical engineering", "Energy systems", "Information engineering"], "Rolls-Royce, BAE Systems, Airbus, McKinsey, Goldman Sachs, ARM Holdings, GCHQ", 98, "£45,000", "Oxford's Engineering Science department offers a uniquely broad 4-year MEng that covers all engineering disciplines before specialisation. Oxford engineers are among the most analytically capable and employable in the world."),
    "imperial": ("https://www.imperial.ac.uk", 5, 5, "GPA 3.51/4.0 — Engineering (REF 2021)", ["Aeronautics and astronautics", "Mechanical engineering and thermofluids", "Electrical and electronic engineering", "Chemical and biomedical engineering", "Computing and control systems"], "Rolls-Royce, BAE Systems, Airbus, Goldman Sachs, McKinsey, ARM Holdings, Shell", 98, "£44,000", "Imperial is the UK's only university dedicated entirely to science and engineering, and its engineering departments are consistently world top 10. The South Kensington campus is adjacent to the Science Museum and surrounded by major engineering employers."),
    "bristol": ("https://www.bristol.ac.uk", 11, 10, "GPA 3.39/4.0 — Engineering (REF 2021)", ["Aerospace engineering (Airbus UK partnership)", "Mechanical and structural engineering", "Electrical and electronic systems", "Civil and structural engineering", "Robotics and autonomous systems"], "Airbus UK (Filton — adjacent to campus), Rolls-Royce, BAE Systems, Leonardo, Ministry of Defence, Goldman Sachs", 95, "£37,000", "Bristol is arguably the UK's premier aerospace engineering destination outside Oxbridge-Imperial, with Airbus UK's main UK engineering centre just 3 miles from campus. Composite materials and aerodynamics research are world-leading."),
    "bath": ("https://www.bath.ac.uk", 9, 8, "GPA 3.20/4.0 — Engineering (REF 2021)", ["Mechanical engineering and thermofluids", "Aerospace engineering", "Electrical and electronic engineering", "Civil and structural engineering", "Biomedical engineering"], "Rolls-Royce, Dyson, Airbus, BAE Systems, JLR, Leonardo, Formula 1 teams", 97, "£37,000", "Bath Engineering is consistently top 5 nationally, with the mandatory Semester 5 placement year giving graduates decisive employability advantage. Bath has particularly strong links to aerospace, automotive and defence employers."),
    "warwick": ("https://warwick.ac.uk", 7, 6, "GPA 3.33/4.0 — Engineering (REF 2021)", ["Electrical and automotive engineering (WMG)", "Mechanical and manufacturing engineering", "Systems engineering", "Power electronics and electric vehicles", "Digital manufacturing"], "JLR (WMG partnership), BMW, Tata Motors, Rolls-Royce, National Grid, Siemens, Goldman Sachs", 95, "£38,000", "Warwick's engineering is distinguished by the Warwick Manufacturing Group (WMG), one of the world's leading automotive and manufacturing research groups with unrivalled industry links. Electric vehicle research is a particular strength."),
    "loughborough": ("https://www.lboro.ac.uk", 6, 5, "GPA 3.21/4.0 — Engineering (REF 2021)", ["Mechanical and manufacturing engineering", "Aerospace engineering", "Electronic and electrical engineering", "Civil engineering", "Automotive engineering"], "Rolls-Royce, McLaren, Red Bull Racing, JLR, BAE Systems, Airbus, Formula 1 teams", 96, "£36,000", "Loughborough is the UK's #1 university for graduate employment in engineering, with extraordinary placement culture. Motorsport and aerospace connections are world-class — McLaren, Red Bull Racing and Rolls-Royce are all regular placement and graduate employers."),
    "manchester": ("https://www.manchester.ac.uk", 16, 14, "GPA 3.30/4.0 — Engineering (REF 2021)", ["Materials science and graphene engineering", "Aerospace and mechanical engineering", "Electrical and electronic systems", "Chemical and process engineering", "Nuclear engineering"], "Rolls-Royce, BAE Systems, National Grid, Graphene spinouts, Siemens, Airbus, Goldman Sachs", 94, "£36,000", "Manchester's Faculty of Science and Engineering has world-class research in materials (National Graphene Institute), nuclear engineering and aerospace. The university's QS top 35 global ranking ensures Manchester engineers are sought after worldwide."),
    "sheffield": ("https://www.sheffield.ac.uk", 19, 17, "GPA 3.11/4.0 — Engineering (REF 2021)", ["Advanced manufacturing (AMRC with Boeing)", "Aerospace and structural engineering", "Electrical and systems engineering", "Materials engineering", "Civil and structural engineering"], "Boeing, Rolls-Royce, BAE Systems, AMRC (on campus), Airbus, Network Rail, National Grid", 93, "£33,000", "Sheffield's AMRC (Advanced Manufacturing Research Centre) with Boeing is one of the world's premier aerospace manufacturing research centres, co-located on campus. Sheffield engineers benefit from direct industry research collaboration from Year 1."),
    "southampton": ("https://www.southampton.ac.uk", 12, 11, "GPA 3.19/4.0 — Engineering (REF 2021)", ["Aeronautics and astronautics", "Mechanical and marine engineering", "Electrical and electronic engineering", "Civil engineering", "Engineering materials and surface science"], "Rolls-Royce, Airbus, BAE Systems, Lloyd's Register, Ordnance Survey, National Grid, IBM", 94, "£34,000", "Southampton's Faculty of Engineering and Physical Sciences has world-leading research in aerodynamics and fluid dynamics, with supersonic wind tunnels on campus. The maritime engineering tradition reflects Southampton's coastal location."),
    "nottingham": ("https://www.nottingham.ac.uk", 17, 16, "GPA 3.15/4.0 — Engineering (REF 2021)", ["Mechanical and aerospace engineering", "Electrical and electronic systems", "Civil and structural engineering", "Manufacturing engineering", "Sustainable energy engineering"], "Rolls-Royce (UTC on campus), BAE Systems, Airbus, Network Rail, National Grid, Capital One (numerical)", 93, "£33,000", "Nottingham's Faculty of Engineering has a Rolls-Royce University Technology Centre on campus focused on advanced manufacturing and gas turbines, giving students direct access to one of engineering's most prestigious employers."),
    "leeds": ("https://www.leeds.ac.uk", 11, 12, "GPA 3.23/4.0 — Engineering (REF 2021)", ["Mechanical engineering and process equipment", "Civil and structural engineering", "Electronic and electrical engineering", "Chemical engineering", "Tribology and surface engineering"], "Rolls-Royce, BAE Systems, Mott MacDonald, Network Rail, Arup, Asda (supply chain engineering), ARUP", 93, "£32,000", "Leeds' School of Engineering has particular strengths in tribology (Institute of Functional Surfaces — world-leading), chemical engineering and civil infrastructure engineering. Strong Yorkshire and North of England engineering employer links."),
    "edinburgh": ("https://www.ed.ac.uk", 5, 6, "GPA 3.33/4.0 — Engineering (REF 2021)", ["Mechanical engineering", "Electrical and electronic systems", "Civil and structural engineering", "Chemical engineering", "Biomedical engineering"], "Rolls-Royce, BAE Systems, SSE (Scottish & Southern Energy), Arup, Scottish Power Renewables, Goldman Sachs, GCHQ", 95, "£36,000", "Edinburgh's School of Engineering has excellent research and teaching across all major engineering disciplines, with particular strengths in energy engineering and biomedical engineering. The Scottish 4-year degree provides valuable engineering breadth."),
    "birmingham": ("https://www.birmingham.ac.uk", 23, 22, "GPA 3.12/4.0 — Engineering (REF 2021)", ["Mechanical and materials engineering", "Electrical and electronic systems", "Civil and structural engineering", "Chemical engineering", "Manufacturing and production engineering"], "JLR (Birmingham HQ area), HSBC (engineering IT), Rolls-Royce, BAE Systems, Network Rail, National Grid, Arup", 93, "£32,000", "Birmingham's School of Engineering has strong research in advanced materials and manufacturing, reflecting the West Midlands' automotive and aerospace engineering heritage. JLR, the UK's largest car manufacturer, is a major employer."),
    "newcastle": ("https://www.ncl.ac.uk", 22, 21, "GPA 3.10/4.0 — Engineering (REF 2021)", ["Mechanical and structural engineering", "Electrical and electronic systems", "Marine engineering and offshore technology", "Chemical engineering", "Civil engineering"], "Rolls-Royce, BAE Systems, Offshore Renewable Energy Catapult, Procter & Gamble, Siemens, Network Rail, Arup", 93, "£32,000", "Newcastle's Faculty of Science, Agriculture and Engineering has particularly strong marine engineering and offshore technology research, reflecting its North Sea heritage and growing offshore wind expertise."),
    "ucl": ("https://www.ucl.ac.uk", 8, 8, "GPA 3.42/4.0 — Engineering (REF 2021)", ["Civil and environmental engineering", "Mechanical engineering", "Electronic and electrical engineering", "Chemical engineering", "Biomedical engineering"], "Arup, Mott MacDonald, Goldman Sachs, BAE Systems, Rolls-Royce, ARM Holdings, Atkins", 96, "£40,000", "UCL's Faculty of Engineering Sciences has world-class research and is located in the heart of London — giving graduates exceptional access to major engineering consultancies, defence firms and the tech sector. UCL's global top 10 ranking ensures high demand from international employers."),
    "queens-belfast": ("https://www.qub.ac.uk", 26, 24, "GPA 3.06/4.0 — Engineering (REF 2021)", ["Aerospace engineering (Spirit AeroSystems/Bombardier)", "Electronic and electrical engineering", "Mechanical and manufacturing engineering", "Civil engineering", "Chemical engineering"], "Spirit AeroSystems (Belfast — major aerospace manufacturer), Bombardier, Catagen, Citi (Belfast tech), Seagate, Thales", 93, "£29,000", "Queen's Engineering is Russell Group and benefits from Belfast's remarkable aerospace cluster — Spirit AeroSystems (the world's largest dedicated aerostructures manufacturer) and Bombardier both have major plants near campus, creating unrivalled aerospace engineering placement opportunities."),
    "glasgow": ("https://www.gla.ac.uk", 20, 19, "GPA 3.31/4.0 — Engineering (REF 2021)", ["Aerospace engineering", "Mechanical engineering", "Electronic and electrical systems", "Civil engineering", "Systems, Power and Energy"], "Rolls-Royce, BAE Systems (Warton), Leonardo (Edinburgh), Scottish Power Renewables, Offshore Renewable Energy Catapult, Spirit AeroSystems", 93, "£33,000", "Glasgow's James Watt School of Engineering (named after the famous Glasgow graduate) has a world-class reputation, particularly in aerospace engineering and power systems. Scotland's growing offshore wind and renewable energy sector is creating strong demand for Glasgow engineers."),
}


def build_maths_entry(slug, website, comp, guard, ref, strengths, employers_str, emp_rate, salary, rep):
    employers = [e.strip() for e in employers_str.split(",")][:7]
    s_key = slug if slug != "university-college-london" else "ucl"
    socs = SOCIALS.get(s_key, SOCIALS.get(slug.replace("-college-london", ""), {}))
    if slug == "university-college-london":
        socs = SOCIALS["ucl"]
    elif slug == "king-s-college-london":
        socs = SOCIALS["kcl"]
    return {
        "website": website,
        "prospectus": f"{website}/study/undergraduate/" if "ox.ac.uk" not in website and "cam.ac.uk" not in website else (
            "https://www.ox.ac.uk/digital-prospectus" if "ox.ac.uk" in website else
            "https://www.undergraduate.study.cam.ac.uk/apply/prospectus"
        ),
        "socials": socs,
        "rankings": {"complete": comp, "guardian": guard, "times": comp, "qsWorld": max(1, comp * 12), "theWorld": max(1, comp * 15), "russellGroup": slug not in ["surrey", "bath", "st-andrews"], "year": "2025"},
        "reputation": rep,
        "fees": {"homeUndergrad": "£9,535/year", "internationalUndergrad": "£22,000–£35,000/year (varies — check university website)", "livingCostEstimate": "See university website"},
        "funding": {"scholarships": ["University merit scholarships — see official website", "International Excellence Award", "University Bursary (means-tested)"], "bursaries": "University Bursary automatically assessed from UCAS.", "paymentPlan": "Fees paid in termly instalments."},
        "employability": {"graduateEmploymentRate": f"{emp_rate}%", "medianSalary": f"{salary} (15 months)", "topEmployers": employers, "careersService": "University Careers Service with mathematics-specific employer events and alumni network.", "placementYearAvailable": True},
        "research": {"refRating": ref, "strengthAreas": strengths, "notableFacilities": ["Mathematics department research and teaching facilities", "High-performance computing cluster", "Shared national mathematics research infrastructure"], "industryPartners": employers[:5]},
        "facilities": {"libraries": ["University Library open late", "Mathematics department library and study areas"], "sportsFacilities": "University sports facilities. 50+ sports clubs.", "studySpaces": "1,500+ study spaces; mathematics study areas.", "labs": "Computing labs with MATLAB, Python, R, Mathematica. Final-year project students work on research problems.", "wellbeing": "Student Wellbeing — counselling, Togetherall (24/7)."},
        "satisfaction": {"nssOverall": 85, "teachingQuality": 88, "academicSupport": 85, "learningResources": 88},
        "travelFromLondon": {"trainTime": "See university website", "trainFromStation": "See university website", "trainToStation": "See university website", "coachTime": "See university website", "drivingTime": "See university website", "distanceMiles": "See university website", "nearestAirport": "See university website"},
        "accessibility": {"disabilityService": "Disability Services — support plans and exam adjustments.", "accessibleAccommodation": "Accessible rooms available. Contact university early.", "mentalHealthSupport": "Counselling service, Togetherall (24/7).", "dyslexiaSupport": "SpLD assessment, study skills and exam adjustments.", "campusAccessibility": "Campus accessibility guide available online."},
        "international": {"visaSupport": "International Student Support — CAS and visa guidance.", "englishRequirements": "IELTS 6.5 overall (6.0 in each component) for most programmes.", "orientationProgramme": "International Welcome Week.", "internationalSocietiesCount": "40+ international and cultural societies", "popularCountries": ["China", "India", "United States", "Germany", "Singapore", "Canada", "Hong Kong"]},
        "contact": {"admissionsEmail": f"admissions@{website.split('//www.')[-1].rstrip('/')}", "admissionsPhone": "See university website", "address": "See university website", "openDayContact": f"opendays@{website.split('//www.')[-1].rstrip('/')}"}
    }


def build_eng_entry(slug, website, comp, guard, ref, strengths, employers_str, emp_rate, salary, rep):
    employers = [e.strip().split("(")[0].strip() for e in employers_str.split(",")][:7]
    s_key = {"imperial": "imperial", "ucl": "ucl", "queens-belfast": "queens-belfast"}.get(slug, slug)
    socs = SOCIALS.get(s_key, {})
    return {
        "website": website,
        "prospectus": f"{website}/study/undergraduate/",
        "socials": socs,
        "rankings": {"complete": comp, "guardian": guard, "times": comp, "qsWorld": max(1, comp * 12), "theWorld": max(1, comp * 15), "russellGroup": slug not in ["loughborough"], "year": "2025"},
        "reputation": rep,
        "fees": {"homeUndergrad": "£9,535/year", "internationalUndergrad": "£22,000–£40,000/year (varies)", "livingCostEstimate": "See university website"},
        "funding": {"scholarships": ["University merit scholarships — see official website", "International Excellence Award", "University Bursary (means-tested)"], "bursaries": "University Bursary automatically assessed from UCAS.", "paymentPlan": "Fees paid in termly instalments."},
        "employability": {"graduateEmploymentRate": f"{emp_rate}%", "medianSalary": f"{salary} (15 months)", "topEmployers": employers, "careersService": "University Careers Service with engineering-specific employer events and industry partnerships.", "placementYearAvailable": True},
        "research": {"refRating": ref, "strengthAreas": strengths, "notableFacilities": ["Engineering department research and teaching labs", "Industry research centres and UTCs", "Shared national engineering research infrastructure"], "industryPartners": employers[:5]},
        "facilities": {"libraries": ["University Library open late", "Engineering department study areas"], "sportsFacilities": "University sports facilities. 50+ sports clubs.", "studySpaces": "1,500+ study spaces; engineering study areas.", "labs": "Modern engineering teaching labs with CAD, FEA, rapid prototyping and measurement equipment.", "wellbeing": "Student Wellbeing — counselling, Togetherall (24/7)."},
        "satisfaction": {"nssOverall": 84, "teachingQuality": 87, "academicSupport": 84, "learningResources": 88},
        "travelFromLondon": {"trainTime": "See university website", "trainFromStation": "See university website", "trainToStation": "See university website", "coachTime": "See university website", "drivingTime": "See university website", "distanceMiles": "See university website", "nearestAirport": "See university website"},
        "accessibility": {"disabilityService": "Disability Services — support plans and exam adjustments.", "accessibleAccommodation": "Accessible rooms available. Contact university early.", "mentalHealthSupport": "Counselling service, Togetherall (24/7).", "dyslexiaSupport": "SpLD assessment, study skills and exam adjustments.", "campusAccessibility": "Campus accessibility guide available online."},
        "international": {"visaSupport": "International Student Support — CAS and visa guidance.", "englishRequirements": "IELTS 6.5 overall (6.0 in each component).", "orientationProgramme": "International Welcome Week.", "internationalSocietiesCount": "40+ international and cultural societies", "popularCountries": ["China", "India", "United States", "Germany", "Malaysia", "Singapore", "Hong Kong"]},
        "contact": {"admissionsEmail": f"admissions@{website.split('//www.')[-1].rstrip('/')}", "admissionsPhone": "See university website", "address": "See university website", "openDayContact": f"opendays@{website.split('//www.')[-1].rstrip('/')}"}
    }


def enrich_file(filepath, data_dict, builder):
    data = json.loads(filepath.read_text(encoding="utf-8-sig"))
    enriched = 0
    for slug, args in data_dict.items():
        if slug not in data:
            print(f"  [SKIP] {slug} not found")
            continue
        if "website" in data[slug]:
            print(f"  [SKIP] {slug} already done")
            continue
        entry = builder(slug, *args)
        data[slug].update(entry)
        print(f"  [OK]   {slug}")
        enriched += 1
    filepath.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    remaining = [s for s, v in data.items() if "website" not in v]
    print(f"  Enriched {enriched}. Remaining: {remaining if remaining else 'none'}")


print("=== MATHS ===")
enrich_file(MATHS_FILE, MATHS_DATA, build_maths_entry)

print("\n=== ENGINEERING ===")
enrich_file(ENG_FILE, ENG_DATA, build_eng_entry)
