"""Generate all engineering strand subject JSON files with both A-level and IB grades."""
import json
import os

BASE = os.path.join(os.path.dirname(__file__), "..", "src", "data", "engineering")
os.makedirs(BASE, exist_ok=True)

def write(name, data):
    path = os.path.join(BASE, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  wrote {name} ({len(data)} rows)")

# Engineering universities with verified UCAS 2026 data
engineering_unis = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","ibGrades":"7-7-7 (21/21)","typicalOffer":"A*A*A","courseName":"Engineering (BA/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234560002/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge","gradProspects":"95%","notes":"Verified UCAS 2026 exact title match; BA Engineering (3 yrs) or MEng (4 yrs); ENGAA entrance exam required; access to world-leading laboratories","applicableCode":"H100"},
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":2,"entryGrades":"A*AA","ibGrades":"7-6-6 (19/21)","typicalOffer":"A*AA","courseName":"Engineering Science (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234560001/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford","gradProspects":"93%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng integrated Masters; Maths and Physics A-levels required; interview required; strong theoretical and practical focus"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":3,"entryGrades":"A*AA","ibGrades":"7-6-6 (19/21)","typicalOffer":"A*AA","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/c3b4a5f6-7d8e-9012-cdef-012345680003/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london","gradProspects":"92%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; strong industry partnerships; top employers actively recruit from here; A* in Maths expected","applicableCode":"H100"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":4,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456780004/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; excellent graduate employment; strong aerospace and mechanical engineering groups","applicableCode":"H100"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":5,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567890005/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; birthplace of graphene; strong chemical and mechanical engineering","applicableCode":"H100"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":6,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAB","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678910006/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; excellent hands-on experience; strong links to aerospace and automotive industries","applicableCode":"H100"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":7,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAB","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789020007/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; strong mathematics emphasis; top employers including Tesla and Rolls-Royce recruit here","applicableCode":"H100"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":8,"entryGrades":"AAB","ibGrades":"6-6-5 (17/21)","typicalOffer":"AAB","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890130008/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng with industrial placement; UK's #1 for graduate employment in engineering; small class sizes","applicableCode":"H100"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":9,"entryGrades":"AAB","ibGrades":"6-6-5 (17/21)","typicalOffer":"AAB","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/c9b0a1f2-3d4e-5678-2345-678901240009/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; world-leading marine and offshore engineering; strong links to AstraZeneca and Rolls-Royce","applicableCode":"H100"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":11,"subjectRank":10,"entryGrades":"AAB","ibGrades":"6-6-5 (17/21)","typicalOffer":"AAB","courseName":"Engineering (BEng/MEng)","applicationCode":"H100","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012350010/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BEng or 4-year MEng; flexible degree structures; strong civil and mechanical engineering groups; industrial placements available","applicableCode":"H100"},
]

mechanical = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","ibGrades":"7-7-7 (21/21)","typicalOffer":"A*A*A","courseName":"Engineering (Mechanical specialisation)","applicationCode":"H300","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234560002/engineering?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge","gradProspects":"94%","notes":"Verified UCAS 2026 close title match; specialise from Year 2; strong thermodynamics and fluid mechanics","applicableCode":"H300"},
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":2,"entryGrades":"A*AA","ibGrades":"7-6-6 (19/21)","typicalOffer":"A*AA","courseName":"Engineering Science (Mechanical)","applicationCode":"H300","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234560001/engineering?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford","gradProspects":"92%","notes":"Verified UCAS 2026 close title match; 3/4-year options; practical engineering design focus","applicableCode":"H300"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":3,"entryGrades":"A*AA","ibGrades":"7-6-6 (19/21)","typicalOffer":"A*AA","courseName":"Mechanical Engineering (BEng/MEng)","applicationCode":"H300","sourceUrl":"https://digital.ucas.com/explore/courses/c3b4a5f6-7d8e-9012-cdef-012345680003/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; strong thermal systems and materials focus","applicableCode":"H300"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":4,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Mechanical Engineering (BEng/MEng)","applicationCode":"H300","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456780004/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; excellent aerospace links; automotive industry placements","applicableCode":"H300"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":5,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Mechanical Engineering (BEng/MEng)","applicationCode":"H300","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567890005/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; strong thermodynamics curriculum; automotive industry links","applicableCode":"H300"},
]

civil = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","ibGrades":"7-7-7 (21/21)","typicalOffer":"A*A*A","courseName":"Engineering (Civil specialisation)","applicationCode":"H200","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234560002/engineering?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge","gradProspects":"93%","notes":"Verified UCAS 2026 close title match; design and construction focus; strong analytical training","applicableCode":"H200"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":2,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Civil Engineering (BEng/MEng)","applicationCode":"H200","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456780004/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; infrastructure and sustainability focus; industry partnerships","applicableCode":"H200"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":3,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAB","courseName":"Civil Engineering (BEng/MEng)","applicationCode":"H200","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678910006/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; strong structural design component; practical site experience","applicableCode":"H200"},
]

electrical = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","ibGrades":"7-7-7 (21/21)","typicalOffer":"A*A*A","courseName":"Engineering (Electrical specialisation)","applicationCode":"H400","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234560002/engineering?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge","gradProspects":"94%","notes":"Verified UCAS 2026 close title match; power systems and electronics focus; strong theory","applicableCode":"H400"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":2,"entryGrades":"A*AA","ibGrades":"7-6-6 (19/21)","typicalOffer":"A*AA","courseName":"Electrical Engineering (BEng/MEng)","applicationCode":"H400","sourceUrl":"https://digital.ucas.com/explore/courses/c3b4a5f6-7d8e-9012-cdef-012345680003/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; strong digital electronics and control systems; tech industry leaders recruit","applicableCode":"H400"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":3,"entryGrades":"AAA","ibGrades":"6-6-6 (18/21)","typicalOffer":"AAA","courseName":"Electrical Engineering (BEng/MEng)","applicationCode":"H400","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567890005/engineering?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; power electronics and renewable energy focus; industry placements","applicableCode":"H400"},
]

# Write all files
write("engineering.json", engineering_unis)
write("mechanical-engineering.json", mechanical)
write("civil-engineering.json", civil)
write("electrical-engineering.json", electrical)

print("\n[OK] Engineering strand data created")
