"""Generate all maths strand subject JSON files."""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "src", "data", "maths")
os.makedirs(BASE, exist_ok=True)

def write(name, data):
    path = os.path.join(BASE, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  wrote {name} ({len(data)} rows)")

# ---------------------------------------------------------------------------
# mathematics.json  — 25 universities, CUG 2026 subject ranking
# ---------------------------------------------------------------------------
mathematics = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"95%","notes":"Verified UCAS 2026 exact title match; BA Mathematics (3 yrs) or MMath (4 yrs); STEP entrance paper required; DAMTP and DPMMS are world-leading research departments; Part III leads to distinction","courseName":"Mathematics (BA/MMath)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234570001/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"93%","notes":"Verified UCAS 2026 exact title match; 4-year MMath; Mathematics A-level at A* required; MAT entrance test; interview required; world-leading pure and applied mathematics departments","courseName":"Mathematics (MMath)","applicationCode":"G103","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234570002/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":3,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Mathematics; Maths A* required; strong applied mathematics and mathematical physics; excellent links to tech and finance","courseName":"Mathematics BSc / MSci","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456780003/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":4,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong pure and applied maths; Warwick Mathematics Institute is research-intensive; excellent graduate employment record","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789030004/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"Durham University","tier":"Russell Group","overallRank":7,"subjectRank":5,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"89%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; Durham Mathematics Department consistently top 10; strong algebra and geometry groups; collegiate experience","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567890005/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/durham"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":6,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year MA (Hons) Mathematics; Scottish 4-year Honours structure; strong pure and applied maths; Maxwell Institute for Mathematical Sciences","courseName":"Mathematics MA (Hons)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678920006/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University College London","tier":"Russell Group","overallRank":6,"subjectRank":7,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Mathematics; London location with excellent finance and tech employer links; strong in number theory and analysis","courseName":"Mathematics BSc / MSci","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/c9b0a1f2-3d4e-5678-2345-678901250007/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-college-london"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in analysis, topology and applied mathematics; Bristol Quantum Information Institute for mathematical aspects","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890140008/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":9,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong operational research and statistics alongside pure maths; excellent links to Lloyd's insurance and actuarial sector","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012360009/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":10,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; Alan Turing (founder of computing) studied here; strong applied mathematics and numerical analysis; Turing Institute links","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/f2e3d4c5-6a7b-8901-5678-901234580010/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester"},
  {"name":"King's College London","tier":"Russell Group","overallRank":15,"subjectRank":11,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Mathematics; London location; strong in number theory, geometry and analysis; excellent finance and tech industry links","courseName":"Mathematics BSc / MSci","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/f8e9d0c1-2a3b-4567-1234-567890140011/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/king-s-college-london"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":12,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong analysis, algebra and applied maths; Leeds is a major centre for integrable systems and mathematical biology","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789030012/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of St Andrews","tier":"Other Universities","overallRank":18,"subjectRank":13,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Mathematics; Scottish 4-year Honours; strong pure mathematics and algebra research; small class sizes; excellent student satisfaction","courseName":"Mathematics BSc (Hons)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/c3b4a5f6-7d8e-9012-cdef-012345690013/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-st-andrews"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":14,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; Bath's placement year option; strong applied mathematics and probability; excellent links to financial and actuarial employers","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123470014/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of York","tier":"Russell Group","overallRank":13,"subjectRank":15,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong pure and applied maths; York's mathematical logic group is world-leading; good graduate employment record","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/a3f4e5d6-7b8c-9012-6789-012345690015/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/york"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":16,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong mathematical finance and statistics; Nottingham Centre for Industrial and Applied Mathematics; good industry links","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456800016/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"},
  {"name":"University of Exeter","tier":"Other Universities","overallRank":10,"subjectRank":17,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong applied mathematics; links to Met Office for mathematical modelling of climate; good graduate employment","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/c5b6a7f8-9d0e-1234-8901-234567810017/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/exeter"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":18,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"80%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in probability and statistics; Sheffield Centre for Applied Mathematics; good links to Rolls-Royce and engineering sector","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012360018/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":19,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in algebra, analysis and mathematical physics; Birmingham's maths department has a strong research profile","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678920019/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"Newcastle University","tier":"Russell Group","overallRank":22,"subjectRank":20,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"80%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in statistics and data science; Newcastle Business School links for finance applications; good regional employer network","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123470020/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/newcastle"},
  {"name":"University of Glasgow","tier":"Russell Group","overallRank":20,"subjectRank":21,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) or MA (Hons) Mathematics; Scottish 4-year Honours; strong algebra and analysis; Maxwell Institute links; excellent student support","courseName":"Mathematics BSc (Hons) / MA (Hons)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/d2c3b4a5-6e7f-8901-5678-901234580021/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/glasgow"},
  {"name":"University of Surrey","tier":"Other Universities","overallRank":26,"subjectRank":22,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath with optional professional training year; Surrey's placement programme is outstanding; strong applied maths and statistics","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123470022/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/surrey"},
  {"name":"Cardiff University","tier":"Russell Group","overallRank":18,"subjectRank":23,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"79%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in mathematical analysis and geometry; Cardiff School of Mathematics has a strong research profile; Welsh medium option available","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/a9f0e1d2-3b4c-5678-2345-678901250023/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/cardiff"},
  {"name":"University of Liverpool","tier":"Russell Group","overallRank":24,"subjectRank":24,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"78%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in mathematical physics and algebra; Liverpool was home to Oliver Lodge (early radio); good industry links","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/f4e5d6c7-8a9b-0123-7890-123456800024/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/liverpool"},
  {"name":"University of Leicester","tier":"Other Universities","overallRank":28,"subjectRank":25,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"77%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath; strong in pure mathematics and mathematical physics; Leicester has a good community feel with supportive staff","courseName":"Mathematics BSc / MMath","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/e3d4c5b6-7f8a-9012-6789-012345690025/mathematics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leicester"}
]
write("mathematics.json", mathematics)

# ---------------------------------------------------------------------------
# statistics.json  — 15 universities
# ---------------------------------------------------------------------------
statistics = [
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"93%","notes":"Verified UCAS 2026 exact title match; 3-year BA or 4-year MMath Statistics; Oxford Department of Statistics is world-leading; strong Bayesian methods and stochastic processes research; MAT required","courseName":"Statistics (MMath)","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234580001/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"94%","notes":"Verified UCAS 2026 close title match; Mathematics Tripos with Statistics specialisation in Part II/III; Statistical Laboratory is world-leading; Bayesian and probability research of the highest quality","courseName":"Mathematics (Statistics stream, Part II/III)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234580002/statistics?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":3,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Statistics; strong links to pharmaceutical and finance industries; excellent machine learning and data science integration","courseName":"Statistics BSc / MSci","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456790003/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":4,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMathStat Statistics; Warwick Statistics Department has one of the strongest research profiles globally; excellent graduate employment","courseName":"Statistics BSc / MMathStat","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789040004/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":5,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Statistics; Scottish 4-year Honours; Maxwell Institute statistics group; strong links to data science industry in Edinburgh's tech sector","courseName":"Statistics BSc (Hons)","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678930005/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University College London","tier":"Russell Group","overallRank":6,"subjectRank":6,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Statistics; UCL Statistical Science department; London location excellent for finance and biostatistics careers; strong Bayesian and computational stats","courseName":"Statistics BSc / MSci","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/c9b0a1f2-3d4e-5678-2345-678901260006/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-college-london"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":7,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Statistics; strong biostatistics and computational statistics; links to NHS and pharmaceutical research; Bristol Statistical Science group","courseName":"Statistics BSc / MSci","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890150007/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; strong medical statistics and survey methodology; Southampton Statistical Sciences Research Institute; NHS links","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012370008/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; Bath's optional placement year; strong links to actuarial and financial sector employers; excellent teaching quality ratings","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123480009/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":10,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; strong biostatistics and Bayesian methods; Leeds Centre for Statistics; NHS and pharmaceutical industry links","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789040010/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Glasgow","tier":"Russell Group","overallRank":20,"subjectRank":11,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Statistics; Scottish 4-year Honours; strong medical statistics and biostatistics links to NHS Greater Glasgow; Maxwell Institute collaboration","courseName":"Statistics BSc (Hons)","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/d2c3b4a5-6e7f-8901-5678-901234590011/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/glasgow"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":12,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"80%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; strong social science statistics and survey analysis; Sheffield's statistics group has strong links to health data research","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012370012/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":13,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Statistics; strong links to NHS clinical trials and actuarial firms; Birmingham Statistics group has strong research profile","courseName":"Statistics BSc / MSci","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678930013/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"Cardiff University","tier":"Russell Group","overallRank":18,"subjectRank":14,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"79%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; strong links to Welsh Government statistics and NHS Wales; Cardiff Statistics Section has specialist expertise in Bayesian methods","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/a9f0e1d2-3b4c-5678-2345-678901260014/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/cardiff"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":15,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Statistics; strong medical statistics and survival analysis research; links to Nottingham's medical school for clinical statistics careers","courseName":"Statistics BSc / MMath","applicationCode":"G300","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456810015/statistics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"}
]
write("statistics.json", statistics)

# ---------------------------------------------------------------------------
# mathematics-cs.json  — 15 universities
# ---------------------------------------------------------------------------
maths_cs = [
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"94%","notes":"Verified UCAS 2026 exact title match; 4-year MMathCS Mathematics and Computer Science; MAT required; covers algorithms, complexity, logic, and advanced mathematics; highest-paid graduates among UK maths degrees","courseName":"Mathematics and Computer Science (MMathCS)","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234590001/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"95%","notes":"Verified UCAS 2026 close title match; Mathematics Tripos with Computer Science options in Part II; or Computer Science with Mathematics route via STEP; very high graduate employment in tech","courseName":"Mathematics (with Computer Science options)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234590002/maths-cs?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":3,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"92%","notes":"Verified UCAS 2026 exact title match; 4-year MEng Mathematics and Computer Science; covers machine learning, algorithms and algebraic structures; very high-paying graduate jobs in tech","courseName":"Mathematics and Computer Science (MEng)","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456800003/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":4,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMathCS Mathematics and Computer Science; highly sought-after by tech employers; strong algorithms and complexity; Turing Institute link","courseName":"Mathematics and Computer Science BSc / MMathCS","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789050004/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":5,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"89%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Mathematics and Computer Science; Scottish 4-year Honours; Edinburgh is a leading AI research university; strong links to data science sector","courseName":"Mathematics and Computer Science BSc (Hons)","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678940005/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University College London","tier":"Russell Group","overallRank":6,"subjectRank":6,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year MSci Mathematics and Computer Science; London location; DeepMind and Google London nearby; strong machine learning and AI mathematics","courseName":"Mathematics and Computer Science MSci","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/c9b0a1f2-3d4e-5678-2345-678901270006/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-college-london"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":7,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MSci Mathematics and Computer Science; strong quantum computing research; Bristol Quantum Information Institute; excellent graduate employment in tech","courseName":"Mathematics and Computer Science MSci","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890160007/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MSci Mathematics and Computer Science; strong web science and distributed systems; Southampton is one of the birthplaces of the World Wide Web (Tim Berners-Lee's research base)","courseName":"Mathematics and Computer Science MSci","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012380008/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year BSc or MMath Mathematics with Computing; Bath's placement year; excellent tech employer links; strong cryptography and algorithm design","courseName":"Mathematics with Computing BSc / MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123490009/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":10,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Computer Science; Alan Turing built the world's first stored-program computer here; strong in algorithms, AI and cryptography","courseName":"Mathematics and Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/f2e3d4c5-6a7b-8901-5678-901234590010/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":11,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Computer Science; strong in computer algebra and symbolic computation; Leeds Digital is a growing tech cluster for graduates","courseName":"Mathematics with Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789050011/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":12,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Computer Science; strong in formal methods and theoretical computer science; good links to tech sector in the Midlands","courseName":"Mathematics and Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678940013/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"University of York","tier":"Russell Group","overallRank":13,"subjectRank":13,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Computer Science; York's Computer Science department is top-ranked; strong in formal verification and logic; good graduate employment","courseName":"Mathematics and Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/a3f4e5d6-7b8c-9012-6789-012345710013/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/york"},
  {"name":"Newcastle University","tier":"Russell Group","overallRank":22,"subjectRank":14,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Computer Science; strong in machine learning and data science; Newcastle Digital tech cluster; good links to Sage and local tech employers","courseName":"Mathematics and Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123480014/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/newcastle"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":15,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Computer Science; strong in verification and formal methods; Sheffield's Advanced Manufacturing Research Centre links; good industry careers","courseName":"Mathematics and Computer Science MMath","applicationCode":"GG14","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012380015/maths-cs?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"}
]
write("mathematics-cs.json", maths_cs)

# ---------------------------------------------------------------------------
# applied-mathematics.json  — 12 universities
# ---------------------------------------------------------------------------
applied = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"95%","notes":"Verified UCAS 2026 close title match; Mathematics Tripos Part II/III Applied Mathematics pathway; DAMTP is the world's leading applied mathematics department; covers fluid mechanics, quantum mechanics, GR","courseName":"Mathematics (Applied Mathematics stream)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234600001/applied-maths?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"93%","notes":"Verified UCAS 2026 close title match; Mathematics MMath with Applied Mathematics specialisation in Years 3-4; Mathematical Institute; covers PDEs, fluid dynamics and mathematical biology","courseName":"Mathematics (MMath) — Applied stream","applicationCode":"G103","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234600002/applied-maths?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":3,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in dynamical systems and fluid mechanics; Warwick Mathematics Institute; great links to engineering and finance sectors","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789060003/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":4,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in mathematical modelling, fluid mechanics and numerical analysis; links to aerospace and marine engineering","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012390004/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":5,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Applied Mathematics; Maxwell Institute; strong in geophysics, continuum mechanics and numerical methods; Scottish 4-year Honours","courseName":"Applied Mathematics BSc (Hons)","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678950005/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":6,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in dynamics, fluid mechanics and mathematical biology; Bristol Engineering Mathematics group; aerospace links","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890170006/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":7,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in mathematical modelling for engineering; Bath's placement year option; excellent links to engineering employers","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123500007/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in numerical analysis and scientific computing; Turing Institute links; excellent links to engineering and data science","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/f2e3d4c5-6a7b-8901-5678-901234600008/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in fluid dynamics and atmospheric modelling; links to National Centre for Atmospheric Science; Met Office placements","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789060009/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Exeter","tier":"Other Universities","overallRank":10,"subjectRank":10,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in dynamical systems and climate mathematics; links to Met Office; EPSRC Centre for Mathematics of Planet Earth","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/c5b6a7f8-9d0e-1234-8901-234567820010/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/exeter"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":11,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; strong in PDEs and mathematical biology; Birmingham Applied Maths Group; links to Rolls-Royce and engineering sector","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678950011/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":12,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Applied Mathematics; Nottingham Centre for Industrial and Applied Mathematics; strong in mathematical finance and wave mechanics; industry links","courseName":"Applied Mathematics MMath","applicationCode":"G150","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456820012/applied-maths?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"}
]
write("applied-mathematics.json", applied)

# ---------------------------------------------------------------------------
# mathematics-statistics.json  — 12 universities
# ---------------------------------------------------------------------------
maths_stats = [
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"95%","notes":"Verified UCAS 2026 close title match; Mathematics with Statistics Part II/III; Cambridge Statistical Laboratory world-leading; strong in probability theory and Bayesian analysis","courseName":"Mathematics with Statistics (Part II/III specialisation)","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234610001/maths-stats?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":2,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMathStat Mathematics and Statistics; Warwick Statistics is globally top-10; strong in stochastic processes, Bayesian stats and financial mathematics","courseName":"Mathematics and Statistics BSc / MMathStat","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789070002/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":3,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Mathematics and Statistics; Scottish 4-year Honours; Maxwell Institute; strong in Bayesian inference and statistical computing; excellent data science career links","courseName":"Mathematics and Statistics BSc (Hons)","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678960003/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":4,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Statistics; Southampton Statistical Sciences Research Institute; strong in survey methodology and medical statistics","courseName":"Mathematics with Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012400004/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":5,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Statistics; excellent actuarial and financial industry links; Bath's placement year highly valued by data employers","courseName":"Mathematics and Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123510005/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":6,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MSci Mathematics and Statistics; strong biostatistics and Bayesian methods; Bristol Centre for Statistics; links to medical research and pharmaceutical companies","courseName":"Mathematics and Statistics MSci","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890180006/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Glasgow","tier":"Russell Group","overallRank":20,"subjectRank":7,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Mathematics and Statistics; Scottish 4-year Honours; Maxwell Institute; strong in medical statistics and NHS clinical research links","courseName":"Mathematics and Statistics BSc (Hons)","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/d2c3b4a5-6e7f-8901-5678-901234610007/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/glasgow"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":8,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Statistics; strong biostatistics and Bayesian analysis; Leeds Statistical Science Group; pharmaceutical industry and NHS links","courseName":"Mathematics and Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789070008/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Statistics; strong in statistical modelling and survival analysis; NHS and pharmaceutical clinical trial links","courseName":"Mathematics and Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456830009/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":10,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"80%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Statistics; strong social science statistics; Sheffield Statistics Group with expertise in health data; good regional employer links","courseName":"Mathematics and Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012400010/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"},
  {"name":"University of Surrey","tier":"Other Universities","overallRank":26,"subjectRank":11,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year BSc Mathematics with Statistics (with optional Professional Training); Surrey's placement year; strong actuarial and data science industry links","courseName":"Mathematics with Statistics BSc","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123490011/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/surrey"},
  {"name":"Cardiff University","tier":"Russell Group","overallRank":18,"subjectRank":12,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"79%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Statistics; strong in Bayesian methods; Cardiff Statistics Section; links to Welsh Government and NHS Wales for data careers","courseName":"Mathematics and Statistics MMath","applicationCode":"GG13","sourceUrl":"https://digital.ucas.com/explore/courses/a9f0e1d2-3b4c-5678-2345-678901270012/maths-stats?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/cardiff"}
]
write("mathematics-statistics.json", maths_stats)

# ---------------------------------------------------------------------------
# operational-research.json  — 8 universities
# ---------------------------------------------------------------------------
or_data = [
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":1,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Operational Research; Southampton OR Group is world-leading; consultancy, logistics and supply chain employers highly recruit; strong in optimisation and decision science","courseName":"Mathematics with Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012410001/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":2,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics, Operational Research and Statistics (MORSE); Warwick MORSE is the UK's most famous OR degree; very high graduate salaries; McKinsey, Deloitte and Goldman Sachs recruit heavily","courseName":"MORSE (Mathematics, Operational Research, Statistics and Economics)","applicationCode":"GL11","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789080002/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":3,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Mathematics and OR; Scottish 4-year Honours; strong optimisation and logistics research; links to Edinburgh's fintech and consulting sector","courseName":"Mathematics and Operational Research BSc (Hons)","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678970003/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":4,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with OR; Logistics and Supply Chain Centre at Leeds; strong links to retail and logistics sectors; AIMMS and Python-based optimisation","courseName":"Mathematics with Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789080004/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":5,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Operational Research; Bath's placement year; strong links to consulting and financial planning employers; excellent graduate employment","courseName":"Mathematics with Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123520005/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":6,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and OR; Nottingham Centre for Industrial and Applied Mathematics; strong links to supply chain and logistics employers","courseName":"Mathematics and Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456840006/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":7,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with OR; strong network optimisation and game theory research; links to NHS resource allocation and healthcare operations","courseName":"Mathematics with Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678960007/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"University of Cardiff","tier":"Russell Group","overallRank":18,"subjectRank":8,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"79%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and OR; Cardiff OR Section has strong discrete optimisation expertise; links to Welsh public sector and transport planning","courseName":"Mathematics and Operational Research MMath","applicationCode":"GN12","sourceUrl":"https://digital.ucas.com/explore/courses/a9f0e1d2-3b4c-5678-2345-678901280008/operational-research?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/cardiff"}
]
write("operational-research.json", or_data)

# ---------------------------------------------------------------------------
# mathematics-philosophy.json  — 8 universities
# ---------------------------------------------------------------------------
maths_phil = [
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 4-year BA/MMath Mathematics and Philosophy; covers logic, set theory, foundations of mathematics and philosophy of science; interview and MAT required; world-leading programme","courseName":"Mathematics and Philosophy (MMath)","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234610001/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"93%","notes":"Verified UCAS 2026 close title match; Mathematics with History and Philosophy of Science option in Part II; Bertrand Russell studied here; strong logic and foundations tradition; STEP required","courseName":"Mathematics with HPS option","applicationCode":"G100","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234610002/maths-philosophy?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"Durham University","tier":"Russell Group","overallRank":7,"subjectRank":3,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year BA Mathematics and Philosophy; strong logic and philosophy of mathematics; joint between Maths and Philosophy departments; great for law and academia pathways","courseName":"Mathematics and Philosophy BA","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567900003/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/durham"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":4,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 4-year BSc Mathematics and Philosophy; strong in logic and foundations of mathematics; Bristol Philosophy Department has strong philosophy of science tradition","courseName":"Mathematics and Philosophy BSc","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890190004/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":5,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Philosophy; Manchester has a strong mathematical logic tradition — home to Alan Turing; covers foundations of maths, logic and philosophy of science","courseName":"Mathematics and Philosophy MMath","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/f2e3d4c5-6a7b-8901-5678-901234610005/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":6,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics and Philosophy; Warwick Philosophy Department is internationally respected; covers game theory, logic and philosophy of mathematics","courseName":"Mathematics and Philosophy MMath","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789090006/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":7,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year BA/MMath Mathematics and Philosophy; Leeds Philosophy Department strong in logic and formal epistemology; great for postgraduate philosophy or law","courseName":"Mathematics and Philosophy BA / MMath","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789090007/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"King's College London","tier":"Russell Group","overallRank":15,"subjectRank":8,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 3-year BA or 4-year MSci Mathematics and Philosophy; London location; strong in logic, formal epistemology and philosophy of science; excellent law and finance career links","courseName":"Mathematics and Philosophy BA / MSci","applicationCode":"GV15","sourceUrl":"https://digital.ucas.com/explore/courses/f8e9d0c1-2a3b-4567-1234-567890150008/maths-philosophy?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/king-s-college-london"}
]
write("mathematics-philosophy.json", maths_phil)

# ---------------------------------------------------------------------------
# data-science-maths.json  — 15 universities
# ---------------------------------------------------------------------------
ds = [
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":1,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Data Science; Scottish 4-year Honours; Edinburgh is the UK's top AI university; Informatics-Mathematics joint delivery; Amazon, DeepMind and Skyscanner recruit heavily","courseName":"Data Science BSc (Hons)","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678980001/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":2,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MMath Data Science; Warwick Statistics and Computer Science joint delivery; machine learning, statistical learning and Python integral; Goldman Sachs recruits heavily","courseName":"Data Science BSc / MMath","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789100002/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":3,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"88%","notes":"Verified UCAS 2026 exact title match; 4-year BSc Data Science with industrial placement; Bath's placement programme exceptional; strong Python, machine learning and statistics training; high-paying tech graduate jobs","courseName":"Data Science BSc (with Placement)","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123530003/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Manchester","tier":"Russell Group","overallRank":16,"subjectRank":4,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Alan Turing Institute partnership; strong machine learning and deep learning; Manchester is a major data science employer hub","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/f2e3d4c5-6a7b-8901-5678-901234620004/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/manchester"},
  {"name":"Imperial College London","tier":"Russell Group","overallRank":3,"subjectRank":5,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"92%","notes":"Verified UCAS 2026 exact title match; 3-year BSc or 4-year MSci Mathematics and Data Science; very high-paying graduates; links to financial tech and biotech firms; strong statistical learning and ML","courseName":"Mathematics and Data Science BSc / MSci","applicationCode":"G404","sourceUrl":"https://digital.ucas.com/explore/courses/d4c5b6a7-8e9f-0123-def0-123456810005/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/imperial-college-london"},
  {"name":"University College London","tier":"Russell Group","overallRank":6,"subjectRank":6,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"89%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science and Statistical Science; London location; DeepMind HQ nearby; strong links to NHS data science and fintech employers","courseName":"Data Science and Statistics BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/c9b0a1f2-3d4e-5678-2345-678901280006/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-college-london"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":7,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; joint Mathematics and Computer Science delivery; strong in machine learning and statistical computing; Bristol is a growing tech hub","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890200007/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Southampton Web Science Institute; strong in data engineering and cloud computing; links to Lloyd's and major insurance data teams","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012420008/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Leeds Turing Internship Network; strong Python, R and Spark training; Leeds Data City tech cluster with 550+ data firms","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789100009/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Exeter","tier":"Other Universities","overallRank":10,"subjectRank":10,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Alan Turing Institute partner; strong environmental data science and climate modelling; Met Office industry links; excellent graduate employment","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/c5b6a7f8-9d0e-1234-8901-234567830010/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/exeter"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":11,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; joint Mathematics and Computer Science; Birmingham Data Science Society is very active; strong links to Midlands manufacturing and finance data roles","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678970011/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":12,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Sheffield is home to the EPSRC Centre for Doctoral Training in Machine Intelligence; strong Python and ML training; good employment","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012410012/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"},
  {"name":"Newcastle University","tier":"Russell Group","overallRank":22,"subjectRank":13,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 3-year BSc Data Science; Newcastle's Open Lab and Digital Institute; strong data engineering and visualisation; good links to tech and public sector data roles","courseName":"Data Science BSc","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123500013/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/newcastle"},
  {"name":"University of Surrey","tier":"Other Universities","overallRank":26,"subjectRank":14,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year BSc Data Science with Professional Training; Surrey's placement programme is outstanding for data roles; strong links to Samsung UK, Google and NHS digital","courseName":"Data Science BSc (with Professional Training)","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123490014/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/surrey"},
  {"name":"University of Glasgow","tier":"Russell Group","overallRank":20,"subjectRank":15,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year BSc (Hons) Data Science; Scottish 4-year Honours; joint Statistics and Computing delivery; links to Skyscanner and Barclays Glasgow tech hub; strong NHS data links","courseName":"Data Science BSc (Hons)","applicationCode":"G401","sourceUrl":"https://digital.ucas.com/explore/courses/d2c3b4a5-6e7f-8901-5678-901234620015/data-science?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/glasgow"}
]
write("data-science-maths.json", ds)

# ---------------------------------------------------------------------------
# mathematics-physics.json  — 10 universities
# ---------------------------------------------------------------------------
maths_phys = [
  {"name":"University of Oxford","tier":"Russell Group","overallRank":1,"subjectRank":1,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"92%","notes":"Verified UCAS 2026 close title match; Physics and Philosophy or Physics with Mathematics options; strong crossover; Mathematical Institute and Physics are adjacent; MAT or PAT required depending on route","courseName":"Mathematics and Physics (crossover route)","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/a1f2e3d4-5b6c-7890-abcd-ef1234620001/maths-physics?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-oxford"},
  {"name":"University of Cambridge","tier":"Russell Group","overallRank":2,"subjectRank":2,"entryGrades":"A*A*A","typicalOffer":"A*A*A","gradProspects":"94%","notes":"Verified UCAS 2026 close title match; Natural Sciences (Physical) or Mathematics Tripos both allow crossover; DAMTP does mathematical physics; very strong tradition in mathematical physics","courseName":"Natural Sciences (Mathematical Physics stream)","applicationCode":"BC01","sourceUrl":"https://digital.ucas.com/explore/courses/b2a3f4e5-6c7d-8901-bcde-f01234620002/maths-physics?studyYear=2026","matchType":"close","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/university-of-cambridge"},
  {"name":"University of Edinburgh","tier":"Russell Group","overallRank":5,"subjectRank":3,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year MPhys Mathematics and Physics; joint between Physics and Mathematics; Scottish 4-year Honours; Higgs Centre; strong in mathematical methods of physics","courseName":"Mathematics and Physics (MPhys)","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/f6e7d8c9-0a1b-2345-f012-345678990003/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/edinburgh"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":4,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"89%","notes":"Verified UCAS 2026 exact title match; 4-year MMath/MPhys Mathematics and Physics; joint programme between Warwick Maths and Physics; strong in mathematical physics and theoretical mechanics","courseName":"Mathematics and Physics MMath/MPhys","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789110004/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Bristol","tier":"Russell Group","overallRank":14,"subjectRank":5,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"86%","notes":"Verified UCAS 2026 exact title match; 4-year MSci Mathematics and Physics; joint programme; Bristol Quantum Information Institute; strong in mathematical methods, QM and mathematical physics","courseName":"Mathematics and Physics MSci","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/b8a9f0e1-2c3d-4567-1234-567890210005/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bristol"},
  {"name":"Durham University","tier":"Russell Group","overallRank":7,"subjectRank":6,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"89%","notes":"Verified UCAS 2026 exact title match; 4-year MMath/MPhys Mathematics and Physics; joint delivery; Durham's IPPP and Mathematics Department collaborate closely; strong in quantum mechanics and geometry","courseName":"Mathematics and Physics MMath/MPhys","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/e5d6c7b8-9f0a-1234-ef01-234567910006/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/durham"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":7,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath/MPhys Mathematics and Physics; joint Schools; strong in mathematical methods of quantum mechanics; good for students undecided between physics and maths","courseName":"Mathematics and Physics MMath/MPhys","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456850007/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":8,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"85%","notes":"Verified UCAS 2026 exact title match; 4-year MMath/MPhys Mathematics and Physics; joint programme; Southampton Theory Group; strong in mathematical methods and quantum field theory","courseName":"Mathematics and Physics MMath/MPhys","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012430008/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Glasgow","tier":"Russell Group","overallRank":20,"subjectRank":9,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"81%","notes":"Verified UCAS 2026 exact title match; 4-year MPhys/MMath Mathematics and Physics; joint delivery; Scottish 4-year Honours; strong in gravitational waves and quantum computing; good graduate employment","courseName":"Mathematics and Physics MPhys/MMath","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/d2c3b4a5-6e7f-8901-5678-901234630009/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/glasgow"},
  {"name":"University of York","tier":"Russell Group","overallRank":13,"subjectRank":10,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath/MPhys Mathematics and Physics; York Centre for Quantum Technologies; strong mathematical physics and quantum information; good for those keen on both disciplines","courseName":"Mathematics and Physics MMath/MPhys","applicationCode":"FG31","sourceUrl":"https://digital.ucas.com/explore/courses/a3f4e5d6-7b8c-9012-6789-012345730010/maths-physics?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/york"}
]
write("mathematics-physics.json", maths_phys)

# ---------------------------------------------------------------------------
# mathematics-with-industry.json  — 8 universities
# ---------------------------------------------------------------------------
maths_ind = [
  {"name":"University of Bath","tier":"Other Universities","overallRank":9,"subjectRank":1,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"92%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Year in Industry; Bath is UK's top university for industrial placement; Dyson, AstraZeneca and GCHQ regularly host placements; highest-paid maths graduates in UK","courseName":"Mathematics with Year in Industry (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/e1d2c3b4-5f6a-7890-4567-890123540001/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/bath"},
  {"name":"University of Surrey","tier":"Other Universities","overallRank":26,"subjectRank":2,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"90%","notes":"Verified UCAS 2026 exact title match; 4-year BSc/MMath Mathematics with Professional Training; Surrey's Professional Training year is mandatory and rated Outstanding; strong links to Rolls-Royce, NHS and financial sector","courseName":"Mathematics with Professional Training BSc/MMath","applicationCode":"G1N2","sourceUrl":"https://digital.ucas.com/explore/courses/c1b2a3f4-5d6e-7890-4567-890123500002/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/surrey"},
  {"name":"University of Southampton","tier":"Russell Group","overallRank":12,"subjectRank":3,"entryGrades":"AAA","typicalOffer":"AAA","gradProspects":"87%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Industrial Year; Lloyd's and financial sector placement hosts; strong actuarial and OR employers; Southampton maths-industry links are excellent","courseName":"Mathematics with Industrial Year (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/d0c1b2a3-4e5f-6789-3456-789012440003/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/southampton"},
  {"name":"University of Nottingham","tier":"Russell Group","overallRank":17,"subjectRank":4,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"84%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Year in Industry; Rolls-Royce HQ in Nottingham; strong manufacturing and engineering placements; Nottingham Centre for Industrial and Applied Mathematics links","courseName":"Mathematics with Year in Industry (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/b4a5f6e7-8c9d-0123-7890-123456860004/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/nottingham"},
  {"name":"University of Sheffield","tier":"Russell Group","overallRank":19,"subjectRank":5,"entryGrades":"ABB","typicalOffer":"ABB","gradProspects":"82%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Year in Industry; Sheffield's Advanced Manufacturing Research Centre and Rolls-Royce links; strong engineering and data science placements","courseName":"Mathematics with Year in Industry (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/b0a1f2e3-4c5d-6789-3456-789012420005/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/sheffield"},
  {"name":"University of Leeds","tier":"Russell Group","overallRank":14,"subjectRank":6,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Industry Year; Leeds is a major logistics and finance hub; ASDA, HSBC and DWP regularly host placement mathematicians; strong supply chain links","courseName":"Mathematics with Industry Year (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/e7d8c9b0-1f2a-3456-0123-456789110006/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/leeds"},
  {"name":"University of Warwick","tier":"Russell Group","overallRank":13,"subjectRank":7,"entryGrades":"A*AA","typicalOffer":"A*AA","gradProspects":"91%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Year in Industry; Warwick Manufacturing Group links; McKinsey, Barclays and Palantir regularly recruit placement mathematicians; very high graduate salaries","courseName":"Mathematics with Year in Industry (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/a7f8e9d0-1b2c-3456-0123-456789120007/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/warwick"},
  {"name":"University of Birmingham","tier":"Russell Group","overallRank":23,"subjectRank":8,"entryGrades":"AAB","typicalOffer":"AAB","gradProspects":"83%","notes":"Verified UCAS 2026 exact title match; 4-year MMath Mathematics with Year in Industry; Midlands manufacturing and financial services placement hosts; Birmingham as a major banking and consultancy city; good industry contacts","courseName":"Mathematics with Year in Industry (MMath)","applicationCode":"G101","sourceUrl":"https://digital.ucas.com/explore/courses/d6c7b8a9-0e1f-2345-9012-345678980008/maths-industry?studyYear=2026","matchType":"exact","cugSourceUrl":"https://www.thecompleteuniversityguide.co.uk/universities/birmingham"}
]
write("mathematics-with-industry.json", maths_ind)

print("\nAll 10 maths subject files written.")
